resources:
- manager.yaml
- service.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/kedacore/keda
  newName: localhost:5001/xxx-sit-stackit-dev-exp-docker-local/cobak/keda/keda
  newTag: main
